server:
    port: 8085
spring:
    application:
        name: orderService
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        name: defaultDataSource
        url: jdbc:mysql://localhost:3306/oa?serverTimezone=UTC
        username: root
        password: root
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848
                cluster-name: CS

#eureka:
#    client:
#        service-url:
#            defaultZone: http://localhost:8081/eureka/